particlesJS("particles-js",
            {
  "particles":{
    "number":{
      "value":97,
      "density":{
        "enable":false,
        "value_area":800
      }
    },
    "color":{
      "value":"#fff"
    },
    "shape":{
      "type":"circle",
      "stroke":{
        "width":0,
        "color":"#000000"
      },
      "image":{
      "src":"images/snowflake.svg",
      "width":100,
      "height":100
      }
    },
    "opacity":{
      "value":0.5,
      "random":true,
      "anim":{
        "enable":true,
        "speed":1,
        "opacity_min":0.1,
        "sync":false
      }
    },
    "size":{
      "value":7,
      "random":true,
      "anim":{
        "enable":true,
        "speed":31,
        "size_min":0.1,
        "sync":false
      }
    },
    "line_linked":{
      "enable":false,
    },
    "move":{
      "enable":true,
      "speed":3,
      "direction":"bottom",
      "random":true,
      "straight":false,
      "out_mode":"out",
      "bounce":false,
      "attract":{
        "enable":false,
      }
    }
  },
  "interactivity":{
    "detect_on":"window",
    "events":{
      "onhover":{
        "enable":true,
          "mode":"bubble"
          },
      "resize":true
    },"modes":{
      "grab":{
        "distance":400,
        "line_linked":{
          "opacity":0.5
      }
    },
      "bubble":{
        "distance":300,
        "size":7,
        "duration":0.3,
        "opacity":1,
        "speed":3
      },
      "repulse":{
        "distance":200,
        "duration":0.3
      }
    }
  }
});